name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.2

    - name: Install Dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/gorilla/mux
        go get -u github.com/pradipsilwal/kubernetes-yaml-generator/database
        go get -u github.com/pradipsilwal/kubernetes-yaml-generator/utils
    
    - name: Run build
      run: go build ./api/main.go
    
    - name: Run vet and lint
      run: |
        go vet ./api/main.go
        golint ./api/main.go
